### ISSUE TITLE
Original Tests Fail

### ISSUE THREAD

**Issue by msosborne3** [learn-co-students/javascript-hand-written-templates-v-000#23]
The test below fails with the error "TypeError: Cannot read property 'be' of undefined".
`it('runs', () => {
    expect(true).to.be.true
  })`

I was able to get it to pass by changing 
`expect(true).to.be.true`
to 
`expect(true).toEqual(true)`

**Comment by peacestone** [comment]
I changed on line 16 from : `expect(true).to.be.true`  to  `expect(true).toBe.true`

**Comment by gj** [comment]
Tests have been removed. Thanks!
